### ISSUE TITLE
Change jpeg output file quality (currently set to default = 75)

### ISSUE THREAD

**Issue by bellavi** [syvaidya/openstego#10]
Is there a way to change jpeg quality setting?

I tried to update the const QUALITY in DCT.java (from 75 to 95) and regenerate the .jar using build.xml, but when I use "Digital Watermarking" the output file sizes are still the same (very little size compared to my original files encoded with quality=95).

It would be nice to be able to configure the wanted jped output files quality, from OpenStego user interface.

**Comment by syvaidya** [comment]
Fixed with v0.7.1

There is no GUI as of now to control JPEG compression. Steps to do it:
- Run OpenStego once - it will create "openstego.ini" file inside user's home directory
- Modify required values in the ini file and then restart OpenStego
