### ISSUE TITLE
javax.imageio.IIOException: Missing Huffman code table entry

### ISSUE THREAD

**Issue by ghost** [syvaidya/openstego#12]
When I try to embed a watermark from a jpeg image it will work if I don't specify the file extension but it will output the original image to bmp. If I try to save the image into a jpeg file it will throw an error:

javax.imageio.IIOException: Missing Huffman code table entry

![See screenshot](https://cloud.githubusercontent.com/assets/6809907/25718037/ebb5f7e8-3104-11e7-9ab5-2f011232b151.png)

**Comment by syvaidya** [comment]
Can you confirm:
* Original file is a valid JPEG file.
* Try changing file extension to "jpg" instead of "jpeg" in output file, and confirm if issue is still there.

**Comment by syvaidya** [comment]
Closing as no response for 2 months.

**Comment by rjoz** [comment]
I just installed OpenStego on macos 10.13.3 (Java 9.0.4) and have the exact same issue.
Valid JPEG file, output file extension jpg

**Comment by syvaidya** [comment]
@rjoz Can you attach the source image here?

**Comment by syvaidya** [comment]
Fixed. Next release would include the same.

**Comment by syvaidya** [comment]
I have release v0.7.3 now. It should have this fix.

**Comment by rjoz** [comment]
I had to increase memory allocation, but it works now, thanks! :-)
