### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by ghost** [syvaidya/openstego#13]
When I try to watermark a hi-res pictur it will throw the "java.lang.OutOfMemoryError: Java heap space" error!

![2017-05-04 1](https://cloud.githubusercontent.com/assets/6809907/25719388/8f9713de-3109-11e7-9208-3efcd08c1f63.png)

**Comment by syvaidya** [comment]
You can try increasing memory allocation in "openstego.bat" file. You'll see one param -Xmx1024m. Change 1024 to 2048 for example.
