### ISSUE TITLE
Blind detection

### ISSUE THREAD

**Issue by DellCliff** [syvaidya/openstego#14]
You're using Dugad's algorithm to embed a watermark into images, as far as I can read your source. Dugad is a blind watermarking technique. I shouldn't need the signature file to read the watermark from the image IMO. Can you adjust the GUI/command line options towards optional signature files?

**Comment by syvaidya** [comment]
Blind algorithm does not mean that it does not need the original signature - it only means that original image is not required. All types of algorithms (blind, semi-blind, non-blind) need original signature for verification. Please refer http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.530.2346&rep=rep1&type=pdf
