### ISSUE TITLE
Error: Illegal key size

### ISSUE THREAD

**Issue by leafcutterant** [syvaidya/openstego#16]
I get this error when trying to encrypt with AES-256. I used the latest Java runtime environment.

**Comment by syvaidya** [comment]
Please install Java Unlimited Strength Jurisdiction Policy Files if you want to use AES 256. By default JRE does not include implementation for high strength cryptography. For Java 8, you can download it from:

http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html

**Comment by leafcutterant** [comment]
Thank you, it worked.
