### ISSUE TITLE
Deb package install fails

### ISSUE THREAD

**Issue by aaron-junot** [syvaidya/openstego#19]
Hello,

I am having trouble installing Open Stego on Debian 9.3 (Stretch).

I downloaded openstego_0.7.2-1_amd64.deb from https://github.com/syvaidya/openstego/releases and installed it using the following: 

```
$ sudo dpkg -i openstego_0.7.2-1_amd64.deb 
[sudo] password for aaron: 
Selecting previously unselected package openstego.
(Reading database ... 126107 files and directories currently installed.)
Preparing to unpack openstego_0.7.2-1_amd64.deb ...
Unpacking openstego (0.7.2-1) ...
Setting up openstego (0.7.2-1) ...
Processing triggers for desktop-file-utils (0.23-1) ...
Processing triggers for mime-support (3.60) ...

$ sudo apt-get install -f
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

```
It created the folder `/usr/share/openstego` and created a link in my Applications dock. When I click the link to open it, I see this error

![screenshot_2018-01-02_11-07-28](https://user-images.githubusercontent.com/2008701/34492584-f66c5fca-efad-11e7-994a-e84b1e1384cf.png)

I tried to run the script manually and cannot.

```
$ ls /usr/share/openstego/
lib  openstego  openstego.png

$ /usr/share/openstego/openstego 
bash: /usr/share/openstego/openstego: /bin/sh^M: bad interpreter: No such file or directory
```

I looked at the contents of the script

```
$ cat /usr/share/openstego/openstego
#!/bin/sh
DIR=$( (cd -P $(dirname $0) && pwd) )
java -Xmx1024m -jar ${DIR}/lib/openstego.jar $*
```
and decided to try to open the jar file manually

```
$ java -Xmx1024m -jar openstego.jar 
java.lang.NullPointerException
	at com.openstego.desktop.util.UserPreferences.init(UserPreferences.java:57)
	at com.openstego.desktop.OpenStego.main(OpenStego.java:429)
```

I'm sure the problem is that I'm doing something wrong, but I'm not sure what it could be. I find it very odd that the files all seem to be there but none of them seem to work.

Do you think it's a problem with my environment or the `deb` file?

Thanks,

Aaron

**Comment by jakewarren** [comment]
@aaron-suarez I had to run `dos2unix` on /usr/share/openstego/openstego to get it to work since it's using DOS line endings.

**Comment by aaron-junot** [comment]
After running dos2unix on /usr/share/openstego/openstego, everything works. Thanks @jakewarren

**Comment by syvaidya** [comment]
Fix would be part of next release.

**Comment by AhmedKAwwad** [comment]
> @aaron-suarez I had to run `dos2unix` on /usr/share/openstego/openstego to get it to work since it's using DOS line endings.
Fixed, Thanks <3
