### ISSUE TITLE
How resilient is the embedding of message into image ?

### ISSUE THREAD

**Issue by GMaxera** [syvaidya/openstego#20]
I wonder if it's possible to extract the embedded message even if the image has been scaled down and/or cropped... and if yes, how much an image can be resized and cropped before the message can't be extracted anymore ?

**Comment by syvaidya** [comment]
"Data Hiding" uses least significant bits of the pixel color values, so it is not *at all* resilient to any change to the image. Message would definitely be lost if it is resized or cropped.
