### ISSUE TITLE
Heap out of memory error

### ISSUE THREAD

**Issue by YPoujol** [syvaidya/openstego#22]
Hi,
I try Openstego to hide a message in JPEG file of 9 Mbytes. The process hang up with an error message "java.lang.OutOfMemoryError".
I try to raise the size of the heap in the .bat file Xmx2048m or Xmx2g. The application does not start up anymore.

The application processes acurately small jpeg files.

Best regards

**Comment by syvaidya** [comment]
Are you using 64-bit JRE? You can't increase Xmx to more than 1.5GB with 32-bit JRE.

**Comment by JacobValdemar** [comment]
I got the same error - was using a 50MB JPG cover file.

**Comment by YPoujol** [comment]
I am using jre 1.8.0-161-b12 X64 on Windows 10.

De : Samir Vaidya [mailto:notifications@github.com] 
Envoyé : samedi 17 février 2018 13:13
À : syvaidya/openstego <openstego@noreply.github.com>
Cc : YPoujol <poujol@club-internet.fr>; Author <author@noreply.github.com>
Objet : Re: [syvaidya/openstego] Heap out of memory error (#22)

 

Are you using 64-bit JRE? You can't increase Xmx to more than 1.5GB with 32-bit JRE.

**Comment by syvaidya** [comment]
If you have 64-bit JRE and have enough RAM you should be able to increase Xmx to 2g or more. If it is not starting, then please post here what error you see. Try starting the app from command line (openstego.bat) - it should show error in command window.

**Comment by syvaidya** [comment]
@JacobValdemar did you try increasing the Xmx to 2g or more?
