### ISSUE TITLE
Unix EOL Broken for Release v0.7.2

### ISSUE THREAD

**Issue by kupiakos** [syvaidya/openstego#25]
Commits 0f1e460 and 4e83898 need to be part of a new release of OpenStego for Linux.

**Comment by syvaidya** [comment]
The fix is NOT yet released. It will be available whenever I do next release.

See comment: https://github.com/syvaidya/openstego/issues/19#issuecomment-366437134

**Comment by syvaidya** [comment]
I have release v0.7.3 now. It should have this fix.
