### ISSUE TITLE
Detected As Malicious

### ISSUE THREAD

**Issue by antuketot76** [syvaidya/openstego#26]
Is this false positive detection?
Scan by Hybrid Analysis.
Hybrid Analysis Link - [HERE](https://www.hybrid-analysis.com/sample/4afc5199e5450091414d72e2ab880237257981d306dddc7832304449b406de6d/5b1ab8c17ca3e1175b32116d)
Scan by Virus Total.
Virus Total Link - [HERE](https://www.virustotal.com/en/file/4afc5199e5450091414d72e2ab880237257981d306dddc7832304449b406de6d/analysis/1528477777/)

**Hybrid Analysis Image**
![image](https://user-images.githubusercontent.com/33280865/41172078-a943a792-6b8d-11e8-8ad8-f022ab5f742f.png)

**Virus Total Image**
![image](https://user-images.githubusercontent.com/33280865/41172110-cb943eec-6b8d-11e8-862a-acf6cdffaa5b.png)

**Comment by syvaidya** [comment]
There is nothing malicious in OpenStego. This has to be a false positive. Anyone can go through the code and build the same binary using build scripts available in the sources.
