### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by sasongko26** [syvaidya/openstego#27]
According to  [openstego.sh](https://github.com/syvaidya/openstego/blob/master/openstego.sh#L4), file lib/openstego.jar not found. there are ant-deb-0.0.1.jar and  nsisant-1.3.jar. 
Did you forget to delete lib/openstego.jar from [.gitignore](https://github.com/syvaidya/openstego/blob/master/.gitignore#L4)?

**Comment by syvaidya** [comment]
Did you download the binary build or source zip? If it is source zip, you need to build the project using Apache Ant.
