### ISSUE TITLE
NO openstego.jar file

### ISSUE THREAD

**Issue by mathewjseelan** [syvaidya/openstego#29]
whenever I try to run the application using the commands, it returns an error 
UNABLE TO ACCESS openstego.jar
also this .jar file is not available in the cloned folder

**Comment by djcopley** [comment]
You have to build it using ant builder. In Linux run `ant -f build.xml` in the openstego directory.

**Comment by syvaidya** [comment]
@djcopley is correct. If you directly want to run, please download prebuilt binaries from release area.
