### ISSUE TITLE
no file extracted

### ISSUE THREAD

**Issue by ArcLampAfterglow** [syvaidya/openstego#30]
"message file successfully extracted from cover file: null"

correct password, win10.

i see this was reported before, and im pretty sure i did a test extraction after i made the file originally.

**Comment by syvaidya** [comment]
Can you please provide more details? It would be good if you can give some test files.

**Comment by ArcLampAfterglow** [comment]
I have since had to replace my computer and don't have access to the
specifics of the situation any longer however the problem resolved itself.

I had embedded a non typed file with 4 lines of text into a png with what I
believe was 0.7.3 however i cannot confirm that now. I just tried to
extract it again after installing 0.7.3 on my new computer and it gave me a
different error, that it was made with an old version. i was able to track
it back to 0.6.1 by installing incrementally older versions and
successfully extract the file which made my night.

Perhaps I originally had 0.6.1 and that is where the error was generated.

Regardless, thanks for the reply!
