### ISSUE TITLE
Compatibility  with previous versions

### ISSUE THREAD

**Issue by GeeK-Batman** [syvaidya/openstego#34]
I have a task for my university module that requires I find hidden files. I have tried using the version they provided of openstego (6.1) but I get java errors and with 7.3 it tells me the version is incompatible. My assumption is the removal of DES Encryption.
Would it be possible to allow this type, for example a check box to choose this but just make it not the default? Surely more options is better?
I'm using Kali if that helps with any of the above.

**Comment by syvaidya** [comment]
DES is a broken algorithm and really unsafe to use, and so I had removed it. If you want to extract data from older versions, couldn't you use older version of OpenStego to extract too?
