### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by ianrelecker** [syvaidya/openstego#36]
Having an issue in v0.7.3 where I am getting a java.lang.OutOfMemoryError. This happens in Data Hiding and Digital Watermarking. I am running Java Version 1.8.0_241. Running 16GB of Ram, OpenStego fully utilizes the CPU and takes about 1200 MB of ram before erroring out.
![Capture](https://user-images.githubusercontent.com/55418500/83557951-4a498200-a4c7-11ea-84e8-651f526bd027.PNG)

**Comment by ianrelecker** [comment]
I am also running the .jar version if that helps!

**Comment by syvaidya** [comment]
This might happen with larger image files. Please increase the JVM memory allocation. In the bat/sh file change -Xmx1024m to -Xmx4096m (4gb allocation). You can increase as required. By the way, you should be using 64-bit java if you want to allocate more than 1.5GB memory.
