### ISSUE TITLE
The documentation lacks explanation of algorithm used for invisible watermark embedding

### ISSUE THREAD

**Issue by manvydasu** [syvaidya/openstego#39]
I was wondering what algorithm was used, but couldn't find it. Without knowing algorithm, it's hard to understand robustness and limitations of implementation. It should probably be mentioned in the readme file somewhere.

**Comment by syvaidya** [comment]
Run OpenStego, and click on Help --> About. It has details of the paper which was the base for algorithm. For watermarking Dugad's algorithm is used (mentioned in that paper).
