### ISSUE TITLE
Linux - Windows versions not cross compatible?

### ISSUE THREAD

**Issue by bonzi9** [syvaidya/openstego#41]
Just stumbled onto this tool to hide sensitive information.

For security reasons I want to use an air-gapped Linux machine to create the files with hidden data, which runs Linux Lite 5.4 from the live USB image. Using OpenStego v0.8.0 on both Windows and Linux.
Testing multiple possibilities to extract the data reliably I found that trying to extract the Linux-created hidden file on Windows 10 (build 10.0.19042.985, 20H2), always results in an error after multiple tries with different image files:

![Extract on Windows error](https://user-images.githubusercontent.com/56406552/120854710-d3cddd00-c57d-11eb-8b5e-1e039732dbd6.PNG)

The (same) file can be created and extracted on Linux without issues:

![Create on linux](https://user-images.githubusercontent.com/56406552/120854705-d3354680-c57d-11eb-8eba-7e2a0c0dda96.png)

![Extract on linux](https://user-images.githubusercontent.com/56406552/120854708-d3cddd00-c57d-11eb-8dc7-2c1a7ae5e24a.png)

Below is the Linux-created .png file with hidden data, the password is   test123   and the embedded data is a file named "New File" which can be opened in a text editor to reveal "test 1 2 3 4 5 6 7 8 9 0".
https://drive.google.com/file/d/1V-np_zQBlDpuMTIqfjsN3Io41txlLg5j/view?usp=sharing

**Comment by syvaidya** [comment]
@bonzi9 it looks like your local file on windows is corrupted (probably while downloading/transferring). I downloaded your file on windows and can successfully extract the message:

![image](https://user-images.githubusercontent.com/3024910/120881070-25ad4c00-c5ec-11eb-8e40-33ed40c8e21b.png)
