### ISSUE TITLE
ARP Entry Does Not Specify Publisher

### ISSUE THREAD

**Issue by Trenly** [syvaidya/openstego#43]
In the Add/Remove Programs entry, the publisher is not specified. This can cause issues with other applications such as the [Windows Package Manager](/microsoft/winget-cli) which depend on ARP data for package matching. 

To fix this, `AppPublisher` should be added to the inno setup

![image](https://user-images.githubusercontent.com/12611259/142772487-a96e30c3-3d1d-47b5-b2ac-180567e1c472.png)

**Comment by syvaidya** [comment]
@Trenly I've added AppPublisher information, but I doubt that it will fix this. The Publisher info in Windows Explorer or in the dialog that comes up about untrusted binary does not come from this field. It can be populated only if I sign the binaries using a valid signature. I don't have a signing key to do that.

**Comment by Trenly** [comment]
> @Trenly I've added AppPublisher information, but I doubt that it will fix this. The Publisher info in Windows Explorer or in the dialog that comes up about untrusted binary does not come from this field. It can be populated only if I sign the binaries using a valid signature. I don't have a signing key to do that.

I’m aware that it doesn’t populate to the explorer dialog. However, for this specific case, as long as it is in the ARP entry, the pacakge should be detected properly when installed
