### ISSUE TITLE
`LSB` plugin not available from RPM?

### ISSUE THREAD

**Issue by rickhg12hs** [syvaidya/openstego#46]
I see the `LSB` plugin in the source, but it doesn't seem to be available from the RPM install.  Is this intended/expected?
```bash
$ openstego algorithms
RandomLSB (Purpose: Data Hiding) - Image based steganography plugin using Random Least Significant Bit algorithm
DWTDugad (Purpose: Watermarking) - Digital watermarking plugin using DWT (Discrete Wavelet Transforms) based on algorithm by Dugad
```

**Comment by syvaidya** [comment]
Yes, this is intentional. LSB was removed long time back as it is very easy to detect. RandomLSB ensures that data gets pseudo-randomly distributed across the cover image, and is harder to detect.

**Comment by rickhg12hs** [comment]
I understand.  Was going to use simple LSB algorithm as an easily discovered/decoded example of steganography for newbies.

Looks like I can add it by creating file `OpenStegoPlugins.external` with contents `com.openstego.desktop.plugin.lsb.LSBPlugin` and then update the contents of `openstego.jar`.
