### ISSUE TITLE
-p not working

### ISSUE THREAD

**Issue by rafaelsorgato** [syvaidya/openstego#48]
-p "123456" doesn't work, the cmd or powershell doesn't recognizes and request a password

example:  java -jar openstego.jar extract -sf "a.bmp" -p "123456"

**Comment by syvaidya** [comment]
@rafaelsorgato could you please give me the command that you used to embed too? I just tried extract with password on command line and I am not able to reproduce the issue.

**Comment by EmilDey** [comment]
i have the same problem. the command to embed with password seems that it is not working.  it generate a image without password.   to try to debuging i use the gui to generate a image with password and extract with the command line.

**Comment by syvaidya** [comment]
@EmilDey can you give me following details:

- OpenStego version
- Operating System
- Java Runtime version
- Sample command that you tried for embedding with password

**Comment by EmilDey** [comment]
i have used the latest version: openstego_0.8.2
linux ubuntu 21.10
java -version output:
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.21.10)
OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.21.10, mixed mode, sharing)

i have tried everything i can imagine:
openstego extract -xf mensaje_out.txt -sf output.png --password="pass"
openstego extract -xf mensaje_out.txt -sf output.png --password=pass
openstego extract -xf mensaje_out.txt -sf output.png -p pass
openstego extract -xf mensaje_out.txt -sf output.png -p "pass"

**Comment by syvaidya** [comment]
Thanks Emil for the details. It was a regression, that I have now fixed with release v0.8.3.
