### ISSUE TITLE
ERROR: JAVA_HOME

### ISSUE THREAD

**Issue by Plagouille** [syvaidya/openstego#50]
Hi,

I can start 0.8.0 but not following versions (0.8.2 and 0.8.3) on 1 boot W10 and no one on another boot W10.

I updated Java runtime, uninstalled, cleaned, reinstalled, but nothing. I did on 2 Windows 10 (dual boot).

![cscript_2022-01-30_15-13-12](https://user-images.githubusercontent.com/76214960/151703433-1229376e-1c5d-4caa-aac0-f12b050197f8.png)
![cscript_2022-01-30_15-19-40](https://user-images.githubusercontent.com/76214960/151703579-63ed2d75-ecda-4637-89fa-61b4c8d485fd.png)
![javaw_2022-01-30_15-33-55](https://user-images.githubusercontent.com/76214960/151704114-5d171ab9-20ee-413f-9628-0a6e9f5fd252.png)

**Comment by syvaidya** [comment]
Java 1.8 is very old and out of support from Oracle for long time. OpenStego needs at least Java 11 now. Please download OpenJDK 11 (or any of the other variants like Oracle JDK, AdoptOpenJDK, etc.). Ensure that `java` is on PATH, or set `JAVA_HOME` environment variable to point to JDK location.
