### ISSUE TITLE
javax.imageio.IIOException: JFIF APP0 must be first marker after SOI.

### ISSUE THREAD

**Issue by Kfont400** [syvaidya/openstego#51]
![2022-02-21](https://user-images.githubusercontent.com/89884205/155049672-e5a568bc-9611-4683-a544-bcec0ed63ff3.png)

Not sure why I'm getting this error or what it exactly means. What do I need to do to clear this error?

**Comment by syvaidya** [comment]
@Kfont400 can you please attach some sample image where you are seeing this, and also what are you trying to do? Watermarking, data hiding?

**Comment by syvaidya** [comment]
@Kfont400 any update on this? Can you attach sample cover file image that is giving this issue?

**Comment by syvaidya** [comment]
Closing for now
