### ISSUE TITLE
Error when trying to embed watermark using my signature

### ISSUE THREAD

**Issue by Nygosaki** [syvaidya/openstego#53]
![image](https://user-images.githubusercontent.com/63132234/177226601-3d29dcba-d118-41e2-b7c5-31472b7e91b6.png)

**Comment by syvaidya** [comment]
Could you please provide more details, or steps to reproduce this issue? What version of OpenStego are you using, etc.?

**Comment by syvaidya** [comment]
Closing for now as there is no information available. Please reopen once you provide it.
