### ISSUE TITLE
Config file is written to home directory, not following XDG base directory spec

### ISSUE THREAD

**Issue by alexruk** [syvaidya/openstego#57]
On linux, openstego.ini is written to $HOME, a mildly irritating location for users which prefer a clean user dir.  I suggest using the [XDG base directory spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).  I can open a PR if needed, but it could be a fairly easy fix to implement for someone who is familiar with the code.

**Comment by syvaidya** [comment]
Fixed with v0.8.6. It also takes care to migrate config from old-style `openstego.ini` file to `<config_home>/openstego/openstego.cfg`
