### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by gianlucavagnuzzi** [syvaidya/openstego#61]
Hi to all,
I wanted to recommend this application to a friend who uses windows but he wanted to pass it on virustotal before installing it and this is the result:
[IMGURL](https://i.imgur.com/kSTJkAJ.png)
Normal? False positive?

**Comment by ghost** [comment]
Since it's say "downloader" i do think it may be the kind of installer that propose you to download other software in it so if you click to fast you have more than you have asked, but i do recommend to verify in a VM to be sure it's that.

**Comment by AGxander** [comment]
**Setup-OpenStego-0.8.6.exe**
VirusTotal said:
   Gridinsoft (no cloud) - **Trojan.Win32.Downloader.sa**
   Cyren - **W32/Delf.VK.gen!Eldorado**
   MaxSecure - **Trojan.Malware.300983.susgen**
   McAfee-GW-Edition - **BehavesLike.Win32.SpyAgent.tc**
   Cynet - **Malicious (score: 100)**
   Google - **Detected**
   Trapmine - **Suspicious.low.ml.score**

**Comment by syvaidya** [comment]
All, I am not really sure why some of these scanners detecting virus in OpenStego. I am pretty sure there is no virus. I think the installer part of the package is causing this false positives. It will help if everyone reports this as false positive to the virus scanning product support.

**Comment by realSZ27** [comment]
its safe
