### ISSUE TITLE
Openstego doesn't Work on my Laptop

### ISSUE THREAD

**Issue by MLaila** [syvaidya/openstego#64]
![Screenshot 2024-02-07 092737](https://github.com/syvaidya/openstego/assets/159274381/b3a4ba57-3c11-48fa-acb7-ba622e1b0415)

I have run Openstego and tried to hide a message as you can see on the screenshot but nothing happens. I don't have any output and sometimes when I repeat the process it blocks completely.

Please can you help me to fix this.

Thanks a lot.

**Comment by syvaidya** [comment]
Could you please provide details:

Operating System
OpenStego version
Java Runtime version

Does this happen for any message or coverfile? If it is specific to some files, then attach those samples too.

**Comment by MLaila** [comment]
Hi Samir,
I thank you for your feedback. This weekend, I found where the issue was. I had installed an old version that didn't work on my laptop. When I reinstalled version 0.8.6, it worked. Thank you.
