### ISSUE TITLE
Trojan Warning!

### ISSUE THREAD

**Issue by alchemissst** [syvaidya/openstego#66]
https://www.virustotal.com/gui/file/80cfa3fe262219ce5e68d255477042e1473aa3ae97552d7bad8e895c95b44a73

![image](https://github.com/user-attachments/assets/978caed4-03a6-447c-a2b7-869dc51fe74b)

**Comment by syvaidya** [comment]
It would help if you can report it as false positive to such automated tools. I am pretty sure that there is no malware or trojan in the binaries I distribute via Github, and I have been reporting false positives to such websites, but it helps if multiple people report it.
