### ISSUE TITLE
Output Stego File as a .JPEG

### ISSUE THREAD

**Issue by macphoto** [syvaidya/openstego#8]
Is it possible to output the hidden message file as a .JPEG?  The .PNG file format **doesn't support metadata fields.** Well, not as many fields. .PNG is omitting some of my metadata info and it's critical that the information be found in the file. This issue is throwing off my workflow too.

**Comment by macphoto** [comment]
Verify Watermark only indicates the strength of the message impression.  But can it preview or extract the hidden impression?

**Comment by syvaidya** [comment]
Unfortunately, answer to both your queries is No.
1. JPEG is a lossy compression format, and it cannot maintain the embedded message fidelity.
2. Whenever image with watermark is modified (e.g. crop, resize, etc), the watermark quality degrades. Even simple saving the file as JPEG can cause watermark to degrade. So only thing that software can do is to verify the strength given the original signature. We can output the extracted signature but it might be gibberish.

**Comment by macphoto** [comment]
Thanks for your reply. 

FYI, I've began using Adobe Bridge to implement the meta data code into the .png file format. Adobe Bridge appears to be the only software that will successfully embed meta data into the .png file format.
